repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: flake8
        args: [
          '--ignore=E501,W503',
        ]

-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.11
      exclude: migrations

-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.3
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-l, --recursive, -x, tests]
        files: .py$
